### ISSUE TITLE
Version management of webots-doc

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#256]
Instead of creating branches specific to a version as we have done for the fist time for Webots 8.5.3, and let the online documentation point on webots-doc master, it would be certainly easier to put all the modifications in master, and let the online documentation point on the git tag matching with the current Webots version.

**Comment by stefaniapedrazzi** [comment]
The disadvantage is that we won't benefit any longer from the latest fixes.
Personally I would still prefer to keep the two different branches, but maybe they can be improved.

**Comment by fabienrohrer** [comment]
This is correct, I'm closing this proposal which has also issues.

I'm worrying about the transition phase as we have to do this morning, when we have to release the documentation of the new Webots version much before the Webots version itself. It the delta time is not too long, I guess it doesn't hurt too much.

**Comment by stefaniapedrazzi** [comment]
What if we change the link to the webots-doc submodule repository so that it doesn't point to master but to the next maintenance release branch?
This way we don't have to publish the new doc too early and if the two branches are synchronized there shouldn't be any issue with the documentation released in the package.
