### ISSUE TITLE
Fix spaces in nodes declaration

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots-doc#286]
The spacing is not consistent between the data type and the field name and between the field name and the default value and between the default value and the comment. Sometimes, we have a minimum amount of spaces (up to 1) and sometimes, we have an arbitrary number of spaces, like here 4 or 5.

**Comment by vincentdm05** [comment]
I think having a minimum amount is better. In the other case whenever a line needs to be added all the others have to be updated which doesn't seem right and increases the chance of conflicts.

**Comment by stefaniapedrazzi** [comment]
Words (fields, name, value) have to be aligned between the lines otherwise it is hard to read them.
About the number of spaces to keep the alignment, then probably one single space is easier to maintain.

**Comment by vincentdm05** [comment]
Maybe a good compromise can be found. We could decide on a maximum number of characters defined by the largest possible label:
- field, hiddenfield, vrmlfield: 12 characters including a trailing space
- SFNode, MFNode, etc: I don't know we'll have to check, hopefully not much more than the smallest one.
- name: that's hard to predict, maybe we could have a convention. We could enforce a max size, such that if it is too large it must be renamed. Or we could enforce a minimum size and if one of them gets over none of the others need to change.

I have noticed we are doing this in the code also, and I really don't like it (mainly because of conflits). I also think it looks silly:
![screen shot 2017-02-08 at 17 15 32](https://cloud.githubusercontent.com/assets/2421402/22745858/3d69f466-ee22-11e6-893b-b6a825ad3c86.png)

**Comment by stefaniapedrazzi** [comment]
It seems that this is what is partially done yet but I have the feeling that doesn't work very well and it is harder to maintain that a single space.

In any case values can be arbitrary long and the same rule won't work for aligning comments.

**Comment by vincentdm05** [comment]
Yes, I am for one space only, and I don't think it is too hard on readability.
I actually think there should never be more than one space except for tabs (2 spaces) and multiline continuity (when a statement does not hold on one line). For tabs, well I think it doesn't need motivation, for multiline since it's a single statement it doesn't break maintainability.

**Comment by stefaniapedrazzi** [comment]
I mean forcing alignment of the current words + 1 space separation from the longest

**Comment by vincentdm05** [comment]
But that is also not maintainable for the reason I mentioned in the second post. Sorry about the confusion, I thought you were talking about one space only without alignment versus aligned with one space.
