### ISSUE TITLE
Integration to the Webots website

### ISSUE THREAD

**Issue by fabienrohrer** [omichel/webots-doc#6]
It is planned to integrate the new documentation to the Cyberbotics website for Webots 8.5.0.

To do this, it seems that the best way is to redirect the `cyberbotics/guide` to `github.io/?index.html?book=guide` and so on.

The redirection may be more or less complex depending on what we would like (GET attribute forging, etc.)

**Comment by omichel** [comment]
Following-up from #16, here is the format I would propose for the online URLs of the documentation:

https://www.cyberbotics.com/doc/book/page?branch=branch&tag=tag#anchor

E.g., for example:

https://www.cyberbotics.com/doc/guide/webots-devices
https://www.cyberbotics.com/doc/reference/camera
https://www.cyberbotics.com/doc/reference/camera#wb_camera_enable
https://www.cyberbotics.com/doc/reference/camera?branch=develop#wb_camera_enable
https://www.cyberbotics.com/doc/reference/camera?tag=8.5
https://www.cyberbotics.com/doc/reference/camera?branch=develop&tag=8.6#wb_camera_enable

Do you agree with that?

**Comment by stefaniapedrazzi** [comment]
What is the branch used for?

**Comment by fabienrohrer** [comment]
It seems very well, clear, standard and concise.
Anchors at the end is a good choice: http://stackoverflow.com/questions/10158283/how-do-i-combine-an-anchor-tag-and-a-pased-variable-in-an-html-href

@stefaniapedrazzi The branch attribute is there to indicate which branch of the repo to display, for a debug purpose. Does this disturb you?

**Comment by stefaniapedrazzi** [comment]
No it doesn't disturb me, but I don't see why it is needed if there is already the tag.

**Comment by omichel** [comment]
Actually, I believe it will be useful when we allow users to edit the doc by themselves. The idea is that at some point, the user could press some "edit" button and get MD page editor similar to https://stackedit.io/editor. When he saves the result, that would actually create a github branch (with his user id as a name for that branch) that he could see immediately on the web site on Cyberbotics when he is logged in, so that he has the feeling that his changes/edit are taken into account. Then, we will receive a PR that we could review and eventually accept and merge into the master branch so that the modification benefits to all.

**Comment by stefaniapedrazzi** [comment]
Ok, so the branch will only be used with the latest version given that we don't allow to modify old documentation.

**Comment by omichel** [comment]
Yes.

**Comment by omichel** [comment]
Therefore, I agree we could make some simplification: We could have only one parameter, such as ?v=<version> where version could be either a tag on the master branch (if it has the format "x.y") or a branch name otherwise.

**Comment by fabienrohrer** [comment]
Yes, `tag` and `branch` are mutual exclusive. I agree to merge them, but I would slightly prefer to have the complete name in order to be self-explanatory: `?version=<version>`

**Comment by omichel** [comment]
Ok, then I am changing to this `?version=<version>`.

**Comment by omichel** [comment]
Implemented in #30.
